server:
  port: 1234

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://josesql/pepesql
    username: pepe
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
